"""Idempotent seed for the technical English vocabulary bank.

Run: python -m app.db.seed_english
"""

from datetime import datetime, timezone

from sqlalchemy import select

from app.db.session import SessionLocal
from app.models import Difficulty, EnglishItem

B = Difficulty.beginner
I = Difficulty.intermediate
A = Difficulty.advanced

ITEMS = [
    # ── networking / beginner ─────────────────────────────────────────────────
    {
        "term": "HTTP",
        "term_pt": "HTTP",
        "definition_en": "A stateless application-layer protocol used for communication between web clients and servers.",
        "definition_pt": "Protocolo de camada de aplicação sem estado usado para comunicação entre clientes e servidores web.",
        "example_sentence": "The browser sends an HTTP GET request to fetch the page.",
        "category": "networking",
        "difficulty": B,
    },
    {
        "term": "port",
        "term_pt": "porta",
        "definition_en": "A numeric identifier (0–65535) that distinguishes different services on the same host.",
        "definition_pt": "Identificador numérico (0–65535) que distingue diferentes serviços no mesmo host.",
        "example_sentence": "The web server listens on port 443 for HTTPS connections.",
        "category": "networking",
        "difficulty": B,
    },
    {
        "term": "socket",
        "term_pt": "socket",
        "definition_en": "An endpoint for two-way communication between processes, identified by IP and port.",
        "definition_pt": "Ponto de extremidade para comunicação bidirecional entre processos, identificado por IP e porta.",
        "example_sentence": "The server opens a socket and binds it to port 8080 before accepting connections.",
        "category": "networking",
        "difficulty": B,
    },
    {
        "term": "DNS",
        "term_pt": "DNS",
        "definition_en": "A distributed naming system that translates human-readable domain names into IP addresses.",
        "definition_pt": "Sistema de nomenclatura distribuído que traduz nomes de domínio legíveis por humanos em endereços IP.",
        "example_sentence": "When you type a URL, a DNS lookup resolves the hostname to an IP address.",
        "category": "networking",
        "difficulty": B,
    },
    {
        "term": "TCP",
        "term_pt": "TCP",
        "definition_en": "A connection-oriented transport protocol that guarantees ordered and reliable delivery of data.",
        "definition_pt": "Protocolo de transporte orientado a conexão que garante entrega ordenada e confiável de dados.",
        "example_sentence": "TCP uses a three-way handshake to establish a connection before data transfer.",
        "category": "networking",
        "difficulty": B,
    },
    {
        "term": "IP address",
        "term_pt": "endereço IP",
        "definition_en": "A numerical label assigned to each device on a network for identification and routing.",
        "definition_pt": "Rótulo numérico atribuído a cada dispositivo em uma rede para identificação e roteamento.",
        "example_sentence": "The server's IP address is 192.168.1.10.",
        "category": "networking",
        "difficulty": B,
    },
    {
        "term": "request",
        "term_pt": "requisição",
        "definition_en": "A message sent from a client to a server asking for a resource or action.",
        "definition_pt": "Mensagem enviada de um cliente para um servidor solicitando um recurso ou ação.",
        "example_sentence": "The client sends a POST request with the user's credentials in the body.",
        "category": "networking",
        "difficulty": B,
    },
    {
        "term": "response",
        "term_pt": "resposta",
        "definition_en": "A message returned by a server to a client after processing a request.",
        "definition_pt": "Mensagem retornada por um servidor a um cliente após processar uma requisição.",
        "example_sentence": "The server sends a 200 OK response with a JSON body.",
        "category": "networking",
        "difficulty": B,
    },
    {
        "term": "header",
        "term_pt": "cabeçalho",
        "definition_en": "Metadata included at the beginning of an HTTP message describing its content or instructions.",
        "definition_pt": "Metadados incluídos no início de uma mensagem HTTP descrevendo seu conteúdo ou instruções.",
        "example_sentence": "The Content-Type header tells the client how to interpret the response body.",
        "category": "networking",
        "difficulty": B,
    },
    {
        "term": "status code",
        "term_pt": "código de status",
        "definition_en": "A three-digit number in an HTTP response indicating the result of the request.",
        "definition_pt": "Número de três dígitos em uma resposta HTTP indicando o resultado da requisição.",
        "example_sentence": "A 404 status code means the requested resource was not found.",
        "category": "networking",
        "difficulty": B,
    },
    # ── networking / intermediate ─────────────────────────────────────────────
    {
        "term": "reverse proxy",
        "term_pt": "proxy reverso",
        "definition_en": "A server that sits in front of backend servers, forwarding client requests and returning responses on their behalf.",
        "definition_pt": "Servidor que fica na frente dos servidores de backend, encaminhando requisições de clientes e retornando respostas em nome deles.",
        "example_sentence": "Nginx acts as a reverse proxy, routing traffic to the appropriate microservice.",
        "category": "networking",
        "difficulty": I,
    },
    {
        "term": "load balancer",
        "term_pt": "balanceador de carga",
        "definition_en": "A component that distributes incoming network traffic across multiple servers to improve availability and throughput.",
        "definition_pt": "Componente que distribui o tráfego de rede de entrada entre vários servidores para melhorar a disponibilidade e o throughput.",
        "example_sentence": "The load balancer uses a round-robin algorithm to spread requests across three backend nodes.",
        "category": "networking",
        "difficulty": I,
    },
    {
        "term": "TLS",
        "term_pt": "TLS",
        "definition_en": "A cryptographic protocol that provides secure communication over a network by encrypting data in transit.",
        "definition_pt": "Protocolo criptográfico que fornece comunicação segura em uma rede ao criptografar dados em trânsito.",
        "example_sentence": "All production traffic is encrypted using TLS 1.3.",
        "category": "networking",
        "difficulty": I,
    },
    {
        "term": "CDN",
        "term_pt": "CDN",
        "definition_en": "A geographically distributed network of servers that caches content closer to end users to reduce latency.",
        "definition_pt": "Rede geograficamente distribuída de servidores que armazena conteúdo em cache mais próximo dos usuários finais para reduzir latência.",
        "example_sentence": "Static assets are served from a CDN so users in different regions get fast download speeds.",
        "category": "networking",
        "difficulty": I,
    },
    {
        "term": "WebSocket",
        "term_pt": "WebSocket",
        "definition_en": "A protocol providing full-duplex communication channels over a single persistent TCP connection.",
        "definition_pt": "Protocolo que fornece canais de comunicação full-duplex sobre uma única conexão TCP persistente.",
        "example_sentence": "The chat application uses WebSocket to push messages to clients in real time.",
        "category": "networking",
        "difficulty": I,
    },
    {
        "term": "CORS",
        "term_pt": "CORS",
        "definition_en": "A browser mechanism that controls which cross-origin HTTP requests are permitted based on server-declared headers.",
        "definition_pt": "Mecanismo de navegador que controla quais requisições HTTP de origens cruzadas são permitidas com base em cabeçalhos declarados pelo servidor.",
        "example_sentence": "The API sets CORS headers to allow requests only from the approved frontend domain.",
        "category": "networking",
        "difficulty": I,
    },
    {
        "term": "throughput",
        "term_pt": "throughput",
        "definition_en": "The rate at which data is successfully transferred over a network in a given time period.",
        "definition_pt": "Taxa na qual os dados são transferidos com sucesso por uma rede em um determinado período de tempo.",
        "example_sentence": "After adding the CDN, the API's throughput increased from 500 to 2000 requests per second.",
        "category": "networking",
        "difficulty": I,
    },
    {
        "term": "latency",
        "term_pt": "latência",
        "definition_en": "The time delay between a request being sent and the corresponding response being received.",
        "definition_pt": "Atraso de tempo entre o envio de uma requisição e o recebimento da resposta correspondente.",
        "example_sentence": "Using a CDN reduced the average latency for European users from 200ms to 40ms.",
        "category": "networking",
        "difficulty": I,
    },
    # ── networking / advanced ─────────────────────────────────────────────────
    {
        "term": "mTLS",
        "term_pt": "mTLS",
        "definition_en": "Mutual TLS, where both client and server authenticate each other using certificates during the handshake.",
        "definition_pt": "TLS mútuo, onde cliente e servidor se autenticam mutuamente usando certificados durante o handshake.",
        "example_sentence": "The internal service mesh uses mTLS to ensure only authorized services can communicate.",
        "category": "networking",
        "difficulty": A,
    },
    {
        "term": "anycast",
        "term_pt": "anycast",
        "definition_en": "A network routing method where the same IP address is assigned to multiple nodes and traffic is routed to the nearest one.",
        "definition_pt": "Método de roteamento de rede onde o mesmo endereço IP é atribuído a vários nós e o tráfego é roteado para o mais próximo.",
        "example_sentence": "DNS resolvers use anycast so queries are automatically answered by the geographically closest server.",
        "category": "networking",
        "difficulty": A,
    },
    {
        "term": "QUIC",
        "term_pt": "QUIC",
        "definition_en": "A transport protocol built on UDP that provides multiplexed streams, built-in encryption, and faster connection setup than TCP.",
        "definition_pt": "Protocolo de transporte construído sobre UDP que fornece streams multiplexados, criptografia embutida e configuração de conexão mais rápida que o TCP.",
        "example_sentence": "HTTP/3 uses QUIC to eliminate head-of-line blocking present in TCP-based HTTP/2.",
        "category": "networking",
        "difficulty": A,
    },
    # ── databases / beginner ──────────────────────────────────────────────────
    {
        "term": "index",
        "term_pt": "índice",
        "definition_en": "A data structure that improves the speed of data retrieval at the cost of additional storage and write overhead.",
        "definition_pt": "Estrutura de dados que melhora a velocidade de recuperação de dados ao custo de armazenamento adicional e sobrecarga de escrita.",
        "example_sentence": "Adding an index on the user_id column reduced the query time from 2s to 5ms.",
        "category": "databases",
        "difficulty": B,
    },
    {
        "term": "query",
        "term_pt": "consulta",
        "definition_en": "A request to retrieve or manipulate data in a database, typically written in SQL.",
        "definition_pt": "Solicitação para recuperar ou manipular dados em um banco de dados, normalmente escrita em SQL.",
        "example_sentence": "The query selects all users created in the last 30 days.",
        "category": "databases",
        "difficulty": B,
    },
    {
        "term": "transaction",
        "term_pt": "transação",
        "definition_en": "A sequence of database operations treated as a single unit that either fully succeeds or fully rolls back.",
        "definition_pt": "Sequência de operações de banco de dados tratada como uma unidade que ou é concluída completamente ou é revertida.",
        "example_sentence": "The transfer deducts from one account and credits another in a single transaction.",
        "category": "databases",
        "difficulty": B,
    },
    {
        "term": "migration",
        "term_pt": "migração",
        "definition_en": "A versioned, incremental change to a database schema that can be applied and rolled back in order.",
        "definition_pt": "Alteração versionada e incremental em um esquema de banco de dados que pode ser aplicada e revertida em ordem.",
        "example_sentence": "The migration adds a nullable email_verified column to the users table.",
        "category": "databases",
        "difficulty": B,
    },
    {
        "term": "foreign key",
        "term_pt": "chave estrangeira",
        "definition_en": "A column that references the primary key of another table to enforce referential integrity.",
        "definition_pt": "Coluna que referencia a chave primária de outra tabela para impor integridade referencial.",
        "example_sentence": "The orders table has a foreign key pointing to users.id.",
        "category": "databases",
        "difficulty": B,
    },
    # ── databases / intermediate ──────────────────────────────────────────────
    {
        "term": "ACID",
        "term_pt": "ACID",
        "definition_en": "A set of database properties (Atomicity, Consistency, Isolation, Durability) that guarantee reliable transaction processing.",
        "definition_pt": "Conjunto de propriedades de banco de dados (Atomicidade, Consistência, Isolamento, Durabilidade) que garantem o processamento confiável de transações.",
        "example_sentence": "PostgreSQL's ACID compliance ensures that a crashed transaction never leaves the database in a partial state.",
        "category": "databases",
        "difficulty": I,
    },
    {
        "term": "N+1 problem",
        "term_pt": "problema N+1",
        "definition_en": "A performance anti-pattern where fetching N records then issuing one additional query per record results in N+1 total queries.",
        "definition_pt": "Anti-padrão de desempenho onde buscar N registros e emitir uma consulta adicional por registro resulta em N+1 consultas no total.",
        "example_sentence": "The ORM was triggering the N+1 problem by lazily loading each post's author in a separate query.",
        "category": "databases",
        "difficulty": I,
    },
    {
        "term": "connection pool",
        "term_pt": "pool de conexões",
        "definition_en": "A cache of reusable database connections that avoids the overhead of opening a new connection for every request.",
        "definition_pt": "Cache de conexões de banco de dados reutilizáveis que evita a sobrecarga de abrir uma nova conexão para cada requisição.",
        "example_sentence": "The connection pool was exhausted because queries were not being closed after execution.",
        "category": "databases",
        "difficulty": I,
    },
    {
        "term": "deadlock",
        "term_pt": "deadlock",
        "definition_en": "A situation where two or more transactions wait indefinitely for each other to release locks.",
        "definition_pt": "Situação em que duas ou mais transações esperam indefinidamente que a outra libere bloqueios.",
        "example_sentence": "The database detected a deadlock and rolled back one of the transactions.",
        "category": "databases",
        "difficulty": I,
    },
    {
        "term": "WAL",
        "term_pt": "WAL",
        "definition_en": "Write-Ahead Log — a durability mechanism where changes are written to a log before being applied to the main data files.",
        "definition_pt": "Write-Ahead Log — mecanismo de durabilidade onde as alterações são gravadas em um log antes de serem aplicadas aos arquivos de dados principais.",
        "example_sentence": "PostgreSQL uses WAL to recover from crashes by replaying logged operations.",
        "category": "databases",
        "difficulty": I,
    },
    # ── databases / advanced ──────────────────────────────────────────────────
    {
        "term": "MVCC",
        "term_pt": "MVCC",
        "definition_en": "Multi-Version Concurrency Control — a technique where each transaction sees a snapshot of the database, avoiding read-write conflicts.",
        "definition_pt": "Controle de Concorrência por Multi-Versão — técnica onde cada transação vê um snapshot do banco de dados, evitando conflitos de leitura e escrita.",
        "example_sentence": "PostgreSQL's MVCC allows readers and writers to operate concurrently without blocking each other.",
        "category": "databases",
        "difficulty": A,
    },
    {
        "term": "write amplification",
        "term_pt": "amplificação de escrita",
        "definition_en": "The ratio of actual bytes written to storage versus logical bytes written, caused by compaction or page rewrites.",
        "definition_pt": "Razão entre bytes reais gravados no armazenamento e bytes lógicos gravados, causada por compactação ou reescrita de páginas.",
        "example_sentence": "LSM-tree engines reduce write amplification for workloads with high insert rates.",
        "category": "databases",
        "difficulty": A,
    },
    {
        "term": "consistent hashing",
        "term_pt": "hash consistente",
        "definition_en": "A hashing scheme where adding or removing a node reassigns only a minimal fraction of keys, enabling smooth horizontal scaling.",
        "definition_pt": "Esquema de hash onde adicionar ou remover um nó redistribui apenas uma fração mínima das chaves, permitindo escalonamento horizontal suave.",
        "example_sentence": "The distributed cache uses consistent hashing so that a node failure only affects the keys it owns.",
        "category": "databases",
        "difficulty": A,
    },
    # ── concurrency / beginner ────────────────────────────────────────────────
    {
        "term": "thread",
        "term_pt": "thread",
        "definition_en": "The smallest unit of CPU execution within a process, sharing the same memory space as other threads.",
        "definition_pt": "Menor unidade de execução da CPU dentro de um processo, compartilhando o mesmo espaço de memória com outras threads.",
        "example_sentence": "The server spawns a new thread for each incoming client connection.",
        "category": "concurrency",
        "difficulty": B,
    },
    {
        "term": "process",
        "term_pt": "processo",
        "definition_en": "An independent program instance with its own memory space, file handles, and execution state.",
        "definition_pt": "Instância de programa independente com seu próprio espaço de memória, handles de arquivo e estado de execução.",
        "example_sentence": "Each worker process in the cluster handles requests independently to isolate failures.",
        "category": "concurrency",
        "difficulty": B,
    },
    {
        "term": "mutex",
        "term_pt": "mutex",
        "definition_en": "A locking primitive that ensures only one thread can access a shared resource at a time.",
        "definition_pt": "Primitiva de bloqueio que garante que apenas uma thread possa acessar um recurso compartilhado por vez.",
        "example_sentence": "The counter update is protected by a mutex to prevent race conditions.",
        "category": "concurrency",
        "difficulty": B,
    },
    {
        "term": "race condition",
        "term_pt": "condição de corrida",
        "definition_en": "A bug where the program's behavior depends on the relative timing of concurrent operations.",
        "definition_pt": "Bug onde o comportamento do programa depende do tempo relativo das operações concorrentes.",
        "example_sentence": "Two goroutines incrementing a counter without synchronization caused a race condition.",
        "category": "concurrency",
        "difficulty": B,
    },
    # ── concurrency / intermediate ────────────────────────────────────────────
    {
        "term": "semaphore",
        "term_pt": "semáforo",
        "definition_en": "A synchronization primitive that controls access to a resource by maintaining a counter of available permits.",
        "definition_pt": "Primitiva de sincronização que controla o acesso a um recurso mantendo um contador de permissões disponíveis.",
        "example_sentence": "A semaphore with count 10 limits the number of concurrent database connections.",
        "category": "concurrency",
        "difficulty": I,
    },
    {
        "term": "event loop",
        "term_pt": "event loop",
        "definition_en": "A programming construct that waits for and dispatches events, enabling non-blocking I/O on a single thread.",
        "definition_pt": "Construção de programação que aguarda e despacha eventos, permitindo I/O não bloqueante em uma única thread.",
        "example_sentence": "Node.js uses an event loop to handle thousands of concurrent connections without spawning a thread per connection.",
        "category": "concurrency",
        "difficulty": I,
    },
    {
        "term": "async/await",
        "term_pt": "async/await",
        "definition_en": "Syntax for writing asynchronous code that reads like synchronous code, suspending execution at await points.",
        "definition_pt": "Sintaxe para escrever código assíncrono que parece código síncrono, suspendendo a execução nos pontos await.",
        "example_sentence": "Using async/await in the route handler allows the server to handle other requests while waiting for the database.",
        "category": "concurrency",
        "difficulty": I,
    },
    {
        "term": "livelock",
        "term_pt": "livelock",
        "definition_en": "A situation where threads keep changing state in response to each other but make no useful progress.",
        "definition_pt": "Situação em que threads ficam mudando de estado em resposta umas às outras, mas não fazem nenhum progresso útil.",
        "example_sentence": "The two processes kept yielding to each other in a livelock, consuming CPU without completing.",
        "category": "concurrency",
        "difficulty": I,
    },
    # ── concurrency / advanced ────────────────────────────────────────────────
    {
        "term": "CAS",
        "term_pt": "CAS",
        "definition_en": "Compare-And-Swap — a CPU atomic instruction that updates a value only if it still matches the expected value.",
        "definition_pt": "Compare-And-Swap — instrução atômica de CPU que atualiza um valor somente se ele ainda corresponder ao valor esperado.",
        "example_sentence": "Lock-free data structures rely on CAS to update shared state without mutexes.",
        "category": "concurrency",
        "difficulty": A,
    },
    {
        "term": "memory model",
        "term_pt": "modelo de memória",
        "definition_en": "A specification that defines which memory operations are visible to which threads and in what order.",
        "definition_pt": "Especificação que define quais operações de memória são visíveis para quais threads e em qual ordem.",
        "example_sentence": "Java's memory model guarantees visibility of volatile writes to all subsequent reads.",
        "category": "concurrency",
        "difficulty": A,
    },
    # ── devops / beginner ─────────────────────────────────────────────────────
    {
        "term": "container",
        "term_pt": "container",
        "definition_en": "A lightweight, isolated environment that packages an application with its dependencies using OS-level virtualization.",
        "definition_pt": "Ambiente leve e isolado que empacota uma aplicação com suas dependências usando virtualização a nível de SO.",
        "example_sentence": "The application runs in a Docker container to ensure consistent behavior across development and production.",
        "category": "devops",
        "difficulty": B,
    },
    {
        "term": "image",
        "term_pt": "imagem",
        "definition_en": "A read-only template containing the filesystem and configuration used to create containers.",
        "definition_pt": "Modelo somente leitura contendo o sistema de arquivos e a configuração usados para criar containers.",
        "example_sentence": "The CI pipeline builds a Docker image and pushes it to the registry.",
        "category": "devops",
        "difficulty": B,
    },
    {
        "term": "environment variable",
        "term_pt": "variável de ambiente",
        "definition_en": "A named value stored in the process's environment, typically used to configure application behavior without changing code.",
        "definition_pt": "Valor nomeado armazenado no ambiente do processo, normalmente usado para configurar o comportamento da aplicação sem alterar o código.",
        "example_sentence": "The database URL is stored in an environment variable so it differs between staging and production.",
        "category": "devops",
        "difficulty": B,
    },
    {
        "term": "pipeline",
        "term_pt": "pipeline",
        "definition_en": "An automated sequence of steps (build, test, deploy) triggered by a code change.",
        "definition_pt": "Sequência automatizada de etapas (build, test, deploy) acionada por uma mudança de código.",
        "example_sentence": "Every pull request triggers the CI pipeline and must pass all tests before merging.",
        "category": "devops",
        "difficulty": B,
    },
    {
        "term": "Dockerfile",
        "term_pt": "Dockerfile",
        "definition_en": "A text file with instructions that Docker uses to build a container image layer by layer.",
        "definition_pt": "Arquivo de texto com instruções que o Docker usa para construir uma imagem de container camada por camada.",
        "example_sentence": "The Dockerfile starts FROM python:3.12-slim and copies the requirements before the source code to maximize cache reuse.",
        "category": "devops",
        "difficulty": B,
    },
    # ── devops / intermediate ─────────────────────────────────────────────────
    {
        "term": "health check",
        "term_pt": "health check",
        "definition_en": "A periodic probe that determines whether a running service is ready to handle traffic.",
        "definition_pt": "Sonda periódica que determina se um serviço em execução está pronto para receber tráfego.",
        "example_sentence": "The load balancer removes a backend from rotation if its health check returns 503 three times in a row.",
        "category": "devops",
        "difficulty": I,
    },
    {
        "term": "rolling deploy",
        "term_pt": "deploy contínuo",
        "definition_en": "A deployment strategy that gradually replaces old instances with new ones to avoid downtime.",
        "definition_pt": "Estratégia de deploy que substitui gradualmente instâncias antigas por novas para evitar tempo de inatividade.",
        "example_sentence": "The rolling deploy updates one pod at a time, ensuring at least two healthy instances are always running.",
        "category": "devops",
        "difficulty": I,
    },
    {
        "term": "secret management",
        "term_pt": "gerenciamento de segredos",
        "definition_en": "The practice of securely storing and distributing sensitive credentials like API keys and passwords.",
        "definition_pt": "Prática de armazenar e distribuir com segurança credenciais sensíveis como chaves de API e senhas.",
        "example_sentence": "API keys are injected at runtime from a vault rather than stored in the repository.",
        "category": "devops",
        "difficulty": I,
    },
    {
        "term": "orchestration",
        "term_pt": "orquestração",
        "definition_en": "Automated management of containerized applications including scheduling, scaling, and networking.",
        "definition_pt": "Gerenciamento automatizado de aplicações em containers, incluindo agendamento, escalabilidade e rede.",
        "example_sentence": "Kubernetes handles orchestration by scheduling containers across the cluster and restarting failed pods.",
        "category": "devops",
        "difficulty": I,
    },
    # ── devops / advanced ─────────────────────────────────────────────────────
    {
        "term": "blue-green deploy",
        "term_pt": "deploy blue-green",
        "definition_en": "A release strategy that maintains two identical environments (blue and green) and switches traffic between them for zero-downtime deployments.",
        "definition_pt": "Estratégia de release que mantém dois ambientes idênticos (blue e green) e alterna o tráfego entre eles para deploys sem tempo de inatividade.",
        "example_sentence": "After validating the green environment, we switch the load balancer to point all traffic to it.",
        "category": "devops",
        "difficulty": A,
    },
    {
        "term": "canary release",
        "term_pt": "release canário",
        "definition_en": "A technique where a new version is gradually rolled out to a small percentage of users before a full release.",
        "definition_pt": "Técnica onde uma nova versão é gradualmente distribuída para uma pequena porcentagem de usuários antes de um release completo.",
        "example_sentence": "The canary release sent 5% of traffic to the new version to monitor error rates before full rollout.",
        "category": "devops",
        "difficulty": A,
    },
    {
        "term": "chaos engineering",
        "term_pt": "engenharia do caos",
        "definition_en": "The practice of deliberately injecting failures into a system to discover weaknesses before they cause outages.",
        "definition_pt": "Prática de injetar deliberadamente falhas em um sistema para descobrir pontos fracos antes que causem interrupções.",
        "example_sentence": "Chaos engineering tests revealed that the service had no fallback when the cache layer became unavailable.",
        "category": "devops",
        "difficulty": A,
    },
    # ── api-design / beginner ─────────────────────────────────────────────────
    {
        "term": "endpoint",
        "term_pt": "endpoint",
        "definition_en": "A specific URL path on a server that handles a particular type of request.",
        "definition_pt": "Caminho de URL específico em um servidor que trata um tipo específico de requisição.",
        "example_sentence": "The POST /users endpoint creates a new user account.",
        "category": "api-design",
        "difficulty": B,
    },
    {
        "term": "payload",
        "term_pt": "payload",
        "definition_en": "The data sent in the body of an HTTP request or response.",
        "definition_pt": "Dados enviados no corpo de uma requisição ou resposta HTTP.",
        "example_sentence": "The payload of the request contains the user's email and password as JSON.",
        "category": "api-design",
        "difficulty": B,
    },
    {
        "term": "authentication",
        "term_pt": "autenticação",
        "definition_en": "The process of verifying the identity of a user or system.",
        "definition_pt": "Processo de verificar a identidade de um usuário ou sistema.",
        "example_sentence": "After authentication, the server issues a JWT to represent the user's session.",
        "category": "api-design",
        "difficulty": B,
    },
    {
        "term": "authorization",
        "term_pt": "autorização",
        "definition_en": "The process of determining what actions an authenticated entity is permitted to perform.",
        "definition_pt": "Processo de determinar quais ações uma entidade autenticada tem permissão para realizar.",
        "example_sentence": "Authorization checks confirm that the user can only edit their own profile.",
        "category": "api-design",
        "difficulty": B,
    },
    # ── api-design / intermediate ─────────────────────────────────────────────
    {
        "term": "idempotent",
        "term_pt": "idempotente",
        "definition_en": "An operation that produces the same result regardless of how many times it is applied.",
        "definition_pt": "Operação que produz o mesmo resultado independentemente de quantas vezes é aplicada.",
        "example_sentence": "PUT /users/42 is idempotent — sending it ten times has the same effect as sending it once.",
        "category": "api-design",
        "difficulty": I,
    },
    {
        "term": "rate limiting",
        "term_pt": "limitação de taxa",
        "definition_en": "A control that restricts how many requests a client can make in a given time window.",
        "definition_pt": "Controle que restringe quantas requisições um cliente pode fazer em uma janela de tempo determinada.",
        "example_sentence": "Rate limiting on the login endpoint allows at most 10 attempts per minute per IP.",
        "category": "api-design",
        "difficulty": I,
    },
    {
        "term": "pagination",
        "term_pt": "paginação",
        "definition_en": "A technique that splits large result sets into discrete pages to limit response size.",
        "definition_pt": "Técnica que divide grandes conjuntos de resultados em páginas discretas para limitar o tamanho da resposta.",
        "example_sentence": "The list endpoint supports pagination via cursor-based navigation to handle millions of records.",
        "category": "api-design",
        "difficulty": I,
    },
    {
        "term": "versioning",
        "term_pt": "versionamento",
        "definition_en": "The practice of maintaining multiple stable API versions simultaneously to avoid breaking existing clients.",
        "definition_pt": "Prática de manter múltiplas versões estáveis de API simultaneamente para evitar quebrar clientes existentes.",
        "example_sentence": "The new breaking change is released under /api/v2 while /api/v1 remains available for existing clients.",
        "category": "api-design",
        "difficulty": I,
    },
    {
        "term": "contract",
        "term_pt": "contrato",
        "definition_en": "A formal agreement between producer and consumer about the shape and behavior of an API.",
        "definition_pt": "Acordo formal entre produtor e consumidor sobre a forma e comportamento de uma API.",
        "example_sentence": "Consumer-driven contract tests verify that the producer's API still satisfies all consumers after a change.",
        "category": "api-design",
        "difficulty": I,
    },
    # ── api-design / advanced ─────────────────────────────────────────────────
    {
        "term": "backward compatibility",
        "term_pt": "compatibilidade retroativa",
        "definition_en": "The ability of a newer API version to work correctly with clients designed for an older version.",
        "definition_pt": "Capacidade de uma versão mais recente da API funcionar corretamente com clientes projetados para uma versão mais antiga.",
        "example_sentence": "Adding a new optional field preserves backward compatibility; removing a required field breaks it.",
        "category": "api-design",
        "difficulty": A,
    },
    {
        "term": "schema evolution",
        "term_pt": "evolução de schema",
        "definition_en": "The process of changing a data schema over time while keeping existing data and clients functional.",
        "definition_pt": "Processo de alterar um schema de dados ao longo do tempo mantendo dados e clientes existentes funcionais.",
        "example_sentence": "The Avro schema evolution strategy allows adding nullable fields without rewriting historical records.",
        "category": "api-design",
        "difficulty": A,
    },
    # ── systems / beginner ────────────────────────────────────────────────────
    {
        "term": "file descriptor",
        "term_pt": "descritor de arquivo",
        "definition_en": "A non-negative integer the OS assigns to an open file, socket, or other I/O resource.",
        "definition_pt": "Inteiro não negativo que o SO atribui a um arquivo aberto, socket ou outro recurso de I/O.",
        "example_sentence": "After calling open(), the process uses the returned file descriptor for all subsequent read and write operations.",
        "category": "systems",
        "difficulty": B,
    },
    {
        "term": "signal",
        "term_pt": "sinal",
        "definition_en": "An asynchronous notification sent to a process to indicate an event such as termination or interruption.",
        "definition_pt": "Notificação assíncrona enviada a um processo para indicar um evento como terminação ou interrupção.",
        "example_sentence": "The process catches SIGTERM to perform graceful shutdown before exiting.",
        "category": "systems",
        "difficulty": B,
    },
    {
        "term": "system call",
        "term_pt": "chamada de sistema",
        "definition_en": "A request from a user-space program to the OS kernel to perform a privileged operation.",
        "definition_pt": "Solicitação de um programa em espaço de usuário ao kernel do SO para executar uma operação privilegiada.",
        "example_sentence": "The read() system call transfers data from the kernel buffer to the process's memory.",
        "category": "systems",
        "difficulty": B,
    },
    # ── systems / intermediate ────────────────────────────────────────────────
    {
        "term": "context switch",
        "term_pt": "troca de contexto",
        "definition_en": "The OS operation of saving the state of one running process and restoring the state of another.",
        "definition_pt": "Operação do SO de salvar o estado de um processo em execução e restaurar o estado de outro.",
        "example_sentence": "Excessive context switches add latency because each switch requires saving and restoring CPU registers.",
        "category": "systems",
        "difficulty": I,
    },
    {
        "term": "page fault",
        "term_pt": "page fault",
        "definition_en": "An exception raised when a process accesses a virtual memory page that is not currently in physical RAM.",
        "definition_pt": "Exceção levantada quando um processo acessa uma página de memória virtual que não está atualmente na RAM física.",
        "example_sentence": "High page fault rates indicate the process's working set does not fit in available RAM.",
        "category": "systems",
        "difficulty": I,
    },
    {
        "term": "mmap",
        "term_pt": "mmap",
        "definition_en": "A system call that maps a file or device into the process's virtual address space for direct memory access.",
        "definition_pt": "Chamada de sistema que mapeia um arquivo ou dispositivo no espaço de endereço virtual do processo para acesso direto à memória.",
        "example_sentence": "The database uses mmap to let the OS manage paging of the data file instead of managing a buffer pool manually.",
        "category": "systems",
        "difficulty": I,
    },
    # ── systems / advanced ────────────────────────────────────────────────────
    {
        "term": "eBPF",
        "term_pt": "eBPF",
        "definition_en": "A kernel technology that lets sandboxed programs run in the OS kernel without changing kernel source code.",
        "definition_pt": "Tecnologia do kernel que permite que programas em sandbox rodem no kernel do SO sem alterar o código fonte do kernel.",
        "example_sentence": "The observability tool uses eBPF to trace system calls with zero-overhead instrumentation.",
        "category": "systems",
        "difficulty": A,
    },
    {
        "term": "NUMA",
        "term_pt": "NUMA",
        "definition_en": "Non-Uniform Memory Access — a CPU design where memory access time depends on whether memory is local or remote to a CPU.",
        "definition_pt": "Non-Uniform Memory Access — design de CPU onde o tempo de acesso à memória depende se a memória é local ou remota a uma CPU.",
        "example_sentence": "The database was pinned to a single NUMA node to avoid cross-node memory latency.",
        "category": "systems",
        "difficulty": A,
    },
    # ── security / beginner ───────────────────────────────────────────────────
    {
        "term": "hashing",
        "term_pt": "hashing",
        "definition_en": "A one-way function that transforms input data into a fixed-length digest that cannot be reversed.",
        "definition_pt": "Função unidirecional que transforma dados de entrada em um resumo de comprimento fixo que não pode ser revertido.",
        "example_sentence": "Passwords are stored as bcrypt hashes so that a database leak does not expose plaintext credentials.",
        "category": "security",
        "difficulty": B,
    },
    {
        "term": "token",
        "term_pt": "token",
        "definition_en": "A self-contained string issued by a server to represent an authenticated session or grant access to a resource.",
        "definition_pt": "String autossuficiente emitida por um servidor para representar uma sessão autenticada ou conceder acesso a um recurso.",
        "example_sentence": "The API accepts a Bearer token in the Authorization header to authenticate requests.",
        "category": "security",
        "difficulty": B,
    },
    {
        "term": "HTTPS",
        "term_pt": "HTTPS",
        "definition_en": "HTTP running over TLS, providing encryption and server authentication for web communication.",
        "definition_pt": "HTTP executado sobre TLS, fornecendo criptografia e autenticação de servidor para comunicação web.",
        "example_sentence": "The browser displays a lock icon when the connection uses HTTPS.",
        "category": "security",
        "difficulty": B,
    },
    # ── security / intermediate ───────────────────────────────────────────────
    {
        "term": "JWT",
        "term_pt": "JWT",
        "definition_en": "JSON Web Token — a compact, self-contained token format for transmitting claims between parties as a signed JSON object.",
        "definition_pt": "JSON Web Token — formato compacto e autossuficiente para transmitir declarações entre partes como um objeto JSON assinado.",
        "example_sentence": "The server signs a JWT with a secret key; clients include it in every request for stateless authentication.",
        "category": "security",
        "difficulty": I,
    },
    {
        "term": "SQL injection",
        "term_pt": "injeção de SQL",
        "definition_en": "An attack that inserts malicious SQL into an input field to manipulate the database query.",
        "definition_pt": "Ataque que insere SQL malicioso em um campo de entrada para manipular a consulta ao banco de dados.",
        "example_sentence": "Using parameterized queries prevents SQL injection by separating data from query logic.",
        "category": "security",
        "difficulty": I,
    },
    {
        "term": "XSS",
        "term_pt": "XSS",
        "definition_en": "Cross-Site Scripting — an attack that injects malicious scripts into web pages viewed by other users.",
        "definition_pt": "Cross-Site Scripting — ataque que injeta scripts maliciosos em páginas web visualizadas por outros usuários.",
        "example_sentence": "Sanitizing user-generated content prevents XSS by removing script tags before rendering.",
        "category": "security",
        "difficulty": I,
    },
    {
        "term": "CSRF",
        "term_pt": "CSRF",
        "definition_en": "Cross-Site Request Forgery — an attack that tricks a user's browser into making unauthorized requests to a site where they are authenticated.",
        "definition_pt": "Cross-Site Request Forgery — ataque que engana o navegador do usuário para fazer requisições não autorizadas a um site onde está autenticado.",
        "example_sentence": "CSRF tokens in forms ensure that state-changing requests originate from the legitimate site.",
        "category": "security",
        "difficulty": I,
    },
    {
        "term": "privilege escalation",
        "term_pt": "escalação de privilégios",
        "definition_en": "The act of exploiting a bug or misconfiguration to gain higher permissions than originally granted.",
        "definition_pt": "Ato de explorar um bug ou configuração incorreta para obter permissões mais elevadas do que as originalmente concedidas.",
        "example_sentence": "The container runs as a non-root user to reduce the blast radius of a privilege escalation exploit.",
        "category": "security",
        "difficulty": I,
    },
    # ── security / advanced ───────────────────────────────────────────────────
    {
        "term": "key derivation",
        "term_pt": "derivação de chave",
        "definition_en": "A function that derives one or more cryptographic keys from a master secret, often with a salt and iteration count.",
        "definition_pt": "Função que deriva uma ou mais chaves criptográficas de um segredo mestre, geralmente com um salt e contagem de iterações.",
        "example_sentence": "PBKDF2 is a key derivation function used to slow down brute-force attacks on stored passwords.",
        "category": "security",
        "difficulty": A,
    },
    {
        "term": "supply chain attack",
        "term_pt": "ataque à cadeia de suprimentos",
        "definition_en": "An attack that compromises software by targeting its dependencies, build tools, or distribution channels.",
        "definition_pt": "Ataque que compromete o software ao visar suas dependências, ferramentas de build ou canais de distribuição.",
        "example_sentence": "The supply chain attack injected malicious code into a popular npm package before release.",
        "category": "security",
        "difficulty": A,
    },
    # ── git-workflow / beginner ───────────────────────────────────────────────
    {
        "term": "commit",
        "term_pt": "commit",
        "definition_en": "A snapshot of changes recorded in the repository history with a message describing what was changed.",
        "definition_pt": "Snapshot de alterações registrado no histórico do repositório com uma mensagem descrevendo o que foi alterado.",
        "example_sentence": "Each commit should represent one logical change and have a clear, imperative-mood message.",
        "category": "git-workflow",
        "difficulty": B,
    },
    {
        "term": "branch",
        "term_pt": "branch",
        "definition_en": "A movable pointer to a commit that lets developers work on isolated changes without affecting the main codebase.",
        "definition_pt": "Ponteiro móvel para um commit que permite aos desenvolvedores trabalhar em mudanças isoladas sem afetar a base de código principal.",
        "example_sentence": "Create a feature branch, work on the change, then open a pull request to merge it into main.",
        "category": "git-workflow",
        "difficulty": B,
    },
    {
        "term": "merge",
        "term_pt": "merge",
        "definition_en": "The operation of integrating changes from one branch into another.",
        "definition_pt": "Operação de integrar mudanças de uma branch em outra.",
        "example_sentence": "After the pull request is approved, merge the feature branch into main.",
        "category": "git-workflow",
        "difficulty": B,
    },
    {
        "term": "pull request",
        "term_pt": "pull request",
        "definition_en": "A proposal to merge changes from one branch into another, typically reviewed by peers before acceptance.",
        "definition_pt": "Proposta de mesclar mudanças de uma branch em outra, normalmente revisada por colegas antes da aceitação.",
        "example_sentence": "The pull request includes a description of the change and a test plan.",
        "category": "git-workflow",
        "difficulty": B,
    },
    {
        "term": "conflict",
        "term_pt": "conflito",
        "definition_en": "A state where two branches have made incompatible changes to the same part of a file that Git cannot automatically resolve.",
        "definition_pt": "Estado em que duas branches fizeram alterações incompatíveis na mesma parte de um arquivo que o Git não consegue resolver automaticamente.",
        "example_sentence": "The merge produced a conflict in the config file that had to be resolved manually.",
        "category": "git-workflow",
        "difficulty": B,
    },
    # ── git-workflow / intermediate ───────────────────────────────────────────
    {
        "term": "rebase",
        "term_pt": "rebase",
        "definition_en": "An operation that moves or replays commits from one branch onto another, rewriting commit history.",
        "definition_pt": "Operação que move ou replay de commits de uma branch para outra, reescrevendo o histórico de commits.",
        "example_sentence": "Rebase the feature branch onto main before opening the pull request to keep a linear history.",
        "category": "git-workflow",
        "difficulty": I,
    },
    {
        "term": "cherry-pick",
        "term_pt": "cherry-pick",
        "definition_en": "An operation that applies a specific commit from one branch to another without merging all commits.",
        "definition_pt": "Operação que aplica um commit específico de uma branch em outra sem mesclar todos os commits.",
        "example_sentence": "The hotfix was cherry-picked from the release branch to apply it to the older supported version.",
        "category": "git-workflow",
        "difficulty": I,
    },
    {
        "term": "reflog",
        "term_pt": "reflog",
        "definition_en": "A Git log of all movements of HEAD and branch tips, useful for recovering lost commits.",
        "definition_pt": "Log do Git de todos os movimentos do HEAD e pontas de branch, útil para recuperar commits perdidos.",
        "example_sentence": "After the accidental reset, the developer used the reflog to find and restore the lost commit.",
        "category": "git-workflow",
        "difficulty": I,
    },
    {
        "term": "stash",
        "term_pt": "stash",
        "definition_en": "A temporary storage area where Git saves uncommitted changes so you can switch branches with a clean working directory.",
        "definition_pt": "Área de armazenamento temporário onde o Git salva mudanças não commitadas para que você possa trocar de branch com um diretório de trabalho limpo.",
        "example_sentence": "Use git stash before switching branches so your in-progress work is not lost.",
        "category": "git-workflow",
        "difficulty": I,
    },
    # ── git-workflow / advanced ───────────────────────────────────────────────
    {
        "term": "bisect",
        "term_pt": "bisect",
        "definition_en": "A Git command that uses binary search over commit history to find the commit that introduced a bug.",
        "definition_pt": "Comando Git que usa busca binária no histórico de commits para encontrar o commit que introduziu um bug.",
        "example_sentence": "Running git bisect narrowed down the regression to a single commit in under five minutes.",
        "category": "git-workflow",
        "difficulty": A,
    },
    {
        "term": "partial clone",
        "term_pt": "clone parcial",
        "definition_en": "A Git feature that defers downloading object data until needed, reducing initial clone size for large repositories.",
        "definition_pt": "Recurso do Git que adia o download de dados de objetos até que sejam necessários, reduzindo o tamanho do clone inicial para repositórios grandes.",
        "example_sentence": "The monorepo uses partial clone so developers only download the blobs they actually access.",
        "category": "git-workflow",
        "difficulty": A,
    },
]


def run() -> None:
    db = SessionLocal()
    try:
        existing_terms = {
            item.term.lower()
            for item in db.scalars(select(EnglishItem)).all()
        }
        added = 0
        now = datetime.now(timezone.utc)
        for data in ITEMS:
            if data["term"].lower() not in existing_terms:
                db.add(
                    EnglishItem(
                        term=data["term"],
                        term_pt=data.get("term_pt"),
                        definition_en=data["definition_en"],
                        definition_pt=data["definition_pt"],
                        example_sentence=data.get("example_sentence"),
                        category=data["category"],
                        difficulty=data["difficulty"],
                        source="seed",
                        created_at=now,
                    )
                )
                added += 1
        db.commit()
        print(f"English seed: {added} items added, {len(existing_terms)} already present.")
    finally:
        db.close()


if __name__ == "__main__":
    run()
